version: "3"
services:
  postgresdb:
    image: postgres
    container_name: postgres-database
    restart: always
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - /var/lib/pgsql
    ports:
      - 5432:5432

  backend:
    image: node:12
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./backend:/var/app
    environment:
      - NODE_ENV=development
    command:
      - /bin/bash
      - -c
      - |
        cd var/app
        yarn run migrate:latest
        yarn start
    depends_on:
      - postgresdb

  frontend:
    image: node:12
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/var/app
    command:
      - /bin/bash
      - -c
      - |
        cd /var/app
        npm start
    depends_on:
      - backend
